_debug_index:
  path: /index
  defaults: { _controller: chameleon_system_debug.debug_test_session_locking_controller:indexAction }

_debug_set:
  path: /set/{value}
  defaults: { _controller: chameleon_system_debug.debug_test_session_locking_controller:setAction }

_debug_get:
  path: /get
  defaults: { _controller: chameleon_system_debug.debug_test_session_locking_controller:getAction }

_debug_lock:
  path: /lock/{duration}
  defaults: { _controller: chameleon_system_debug.debug_test_session_locking_controller:lockAction }
  requirements:
    duration: "\d+"
